### ISSUE TITLE
LinkedIn video broken

### ISSUE THREAD

**Issue by itsKV** [cowlicks/privacypossum#67]
* browser name and version - Mozilla Firefox 60.0.1
* privacy possum version - 2018.5.24

Clicking on PLAY button on LinkedIn video never plays any video if Possum is enabled on LinkedIn.
Whenever I disables it, videos plays perfect.

**Comment by cowlicks** [comment]
hello @itsKV 

I'm having trouble reproducing this. When I visit https://blog.linkedin.com/2017/august/22/Introducing-LinkedIn-Video-Show-Your-Experience-and-Perspective

I'm able to watch the video. Maybe it is because I am not logged in?

Whether or not I'm able to reproduce this, I would guess this has to do with referer headers getting stripped. If that is true #66 should fix it.

**Comment by cowlicks** [comment]
Closing for staleness. Please re-open if this is still an issue.

**Comment by itsKV** [comment]
This still happens. I don't know why. As soon as I disables PP for LinkedIn, all LinkedIn videos works fine.
I am not CSE grad, so, I can't comment the technical cause behind this, but PP is definitely breaking LinekdIn videos.
Is there I can help anyway? I would be greatful. 
Thanks

**Comment by cowlicks** [comment]
@itsKV thank you for the response, I'll reopen the issue. I think I'll have to create a linked in account to figure investigate this.
